------------ core require ------------
require('core.Class')
util = require("3rd.xlua.util")
require('3rd.utf8')
require('3rd.xstr')
require("3rd.json")
require("3rd.list")
require("3rd.event")
require("3rd.ltn12")
require("3rd.unity.Mathf")
require("3rd.unity.Vector3")
require("core.Logger")
require("core.Global")
require("core.CsClassName")
require("core.utils.LuaUtil")
require("core.utils.TableUtil")
require("core.utils.StringUtil")
require("core.Main")
------------ game require ------------

Main:HotfixMain()
